<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit_ultimate_410
{
    public static $files = array (
        '99ef6fcc525faf8b52e78a1545be830c' => __DIR__ . '/../..' . '/functions/do_settings_section.php',
    );

    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'TinyWeb\\Ultimate410\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'TinyWeb\\Ultimate410\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit_ultimate_410::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit_ultimate_410::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
