<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '99ef6fcc525faf8b52e78a1545be830c' => $baseDir . '/functions/do_settings_section.php',
);
